gUnknown_08050968: @ 0x08050968
	.incbin "sound/direct_sound_samples/08050968.bin"
gUnknown_08052EA4: @ 0x08052EA4
	.incbin "sound/direct_sound_samples/08052EA4.bin"
gUnknown_08055078: @ 0x08055078
	.incbin "sound/direct_sound_samples/08055078.bin"
gUnknown_08057180: @ 0x08057180
	.incbin "sound/direct_sound_samples/08057180.bin"
gUnknown_08059E48: @ 0x08059E48
	.incbin "sound/direct_sound_samples/08059E48.bin"
gUnknown_0805B61C: @ 0x0805B61C
	.incbin "sound/direct_sound_samples/0805B61C.bin"
gUnknown_0805DE78: @ 0x0805DE78
	.incbin "sound/direct_sound_samples/0805DE78.bin"
gUnknown_0805E7C4: @ 0x0805E7C4
	.incbin "sound/direct_sound_samples/0805E7C4.bin"
gUnknown_080633F0: @ 0x080633F0
	.incbin "sound/direct_sound_samples/080633F0.bin"
gUnknown_080639FC: @ 0x080639FC
	.incbin "sound/direct_sound_samples/080639FC.bin"
gUnknown_0806518C: @ 0x0806518C
	.incbin "sound/direct_sound_samples/0806518C.bin"
gUnknown_08065C30: @ 0x08065C30
	.incbin "sound/direct_sound_samples/08065C30.bin"
gUnknown_08069FC4: @ 0x08069FC4
	.incbin "sound/direct_sound_samples/08069FC4.bin"
gUnknown_0806C634: @ 0x0806C634
	.incbin "sound/direct_sound_samples/0806C634.bin"
gUnknown_0806E480: @ 0x0806E480
	.incbin "sound/direct_sound_samples/0806E480.bin"
gUnknown_08071FDC: @ 0x08071FDC
	.incbin "sound/direct_sound_samples/08071FDC.bin"
gUnknown_0807345C: @ 0x0807345C
	.incbin "sound/direct_sound_samples/0807345C.bin"
gUnknown_0807A540: @ 0x0807A540
	.incbin "sound/direct_sound_samples/0807A540.bin"
gUnknown_0807D754: @ 0x0807D754
	.incbin "sound/direct_sound_samples/0807D754.bin"
gUnknown_0808180C: @ 0x0808180C
	.incbin "sound/direct_sound_samples/0808180C.bin"
gUnknown_08082BE8: @ 0x08082BE8
	.incbin "sound/direct_sound_samples/08082BE8.bin"
gUnknown_0808533C: @ 0x0808533C
	.incbin "sound/direct_sound_samples/0808533C.bin"
gUnknown_0808A9F4: @ 0x0808A9F4
	.incbin "sound/direct_sound_samples/0808A9F4.bin"
gUnknown_0808CEEC: @ 0x0808CEEC
	.incbin "sound/direct_sound_samples/0808CEEC.bin"
gUnknown_0808DAEC: @ 0x0808DAEC
	.incbin "sound/direct_sound_samples/0808DAEC.bin"
gUnknown_0808F568: @ 0x0808F568
	.incbin "sound/direct_sound_samples/0808F568.bin"
gUnknown_08090620: @ 0x08090620
	.incbin "sound/direct_sound_samples/08090620.bin"
gUnknown_08091864: @ 0x08091864
	.incbin "sound/direct_sound_samples/08091864.bin"
gUnknown_08092AD0: @ 0x08092AD0
	.incbin "sound/direct_sound_samples/08092AD0.bin"
gUnknown_08093C0C: @ 0x08093C0C
	.incbin "sound/direct_sound_samples/08093C0C.bin"
gUnknown_080963E0: @ 0x080963E0
	.incbin "sound/direct_sound_samples/080963E0.bin"
gUnknown_0809901C: @ 0x0809901C
	.incbin "sound/direct_sound_samples/0809901C.bin"
gUnknown_0809AFFC: @ 0x0809AFFC
	.incbin "sound/direct_sound_samples/0809AFFC.bin"
gUnknown_0809B96C: @ 0x0809B96C
	.incbin "sound/direct_sound_samples/0809B96C.bin"
gUnknown_0809F274: @ 0x0809F274
	.incbin "sound/direct_sound_samples/0809F274.bin"
gUnknown_080A0648: @ 0x080A0648
	.incbin "sound/direct_sound_samples/080A0648.bin"
gUnknown_080A1DB8: @ 0x080A1DB8
	.incbin "sound/direct_sound_samples/080A1DB8.bin"
gUnknown_080A5824: @ 0x080A5824
	.incbin "sound/direct_sound_samples/080A5824.bin"
gUnknown_080A5B68: @ 0x080A5B68
	.incbin "sound/direct_sound_samples/080A5B68.bin"
gUnknown_080A5EC4: @ 0x080A5EC4
	.incbin "sound/direct_sound_samples/080A5EC4.bin"
gUnknown_080A71F8: @ 0x080A71F8
	.incbin "sound/direct_sound_samples/080A71F8.bin"
gUnknown_080A8A54: @ 0x080A8A54
	.incbin "sound/direct_sound_samples/080A8A54.bin"
gUnknown_080A9FF8: @ 0x080A9FF8
	.incbin "sound/direct_sound_samples/080A9FF8.bin"
gUnknown_080AB55C: @ 0x080AB55C
	.incbin "sound/direct_sound_samples/080AB55C.bin"
gUnknown_080AC830: @ 0x080AC830
	.incbin "sound/direct_sound_samples/080AC830.bin"
gUnknown_080B0C84: @ 0x080B0C84
	.incbin "sound/direct_sound_samples/080B0C84.bin"
gUnknown_080B1EA0: @ 0x080B1EA0
	.incbin "sound/direct_sound_samples/080B1EA0.bin"
gUnknown_080B3008: @ 0x080B3008
	.incbin "sound/direct_sound_samples/080B3008.bin"
gUnknown_080B7464: @ 0x080B7464
	.incbin "sound/direct_sound_samples/080B7464.bin"
gUnknown_080B7FD8: @ 0x080B7FD8
	.incbin "sound/direct_sound_samples/080B7FD8.bin"
gUnknown_080BB4AC: @ 0x080BB4AC
	.incbin "sound/direct_sound_samples/080BB4AC.bin"
gUnknown_080C38CC: @ 0x080C38CC
	.incbin "sound/direct_sound_samples/080C38CC.bin"
gUnknown_080C3EC4: @ 0x080C3EC4
	.incbin "sound/direct_sound_samples/080C3EC4.bin"
gUnknown_080C510C: @ 0x080C510C
	.incbin "sound/direct_sound_samples/080C510C.bin"
gUnknown_080C5308: @ 0x080C5308
	.incbin "sound/direct_sound_samples/080C5308.bin"
gUnknown_080C6308: @ 0x080C6308
	.incbin "sound/direct_sound_samples/080C6308.bin"
gUnknown_080D0810: @ 0x080D0810
	.incbin "sound/direct_sound_samples/080D0810.bin"
gUnknown_080D9EE0: @ 0x080D9EE0
	.incbin "sound/direct_sound_samples/080D9EE0.bin"
gUnknown_080DF778: @ 0x080DF778
	.incbin "sound/direct_sound_samples/080DF778.bin"
gUnknown_080E290C: @ 0x080E290C
	.incbin "sound/direct_sound_samples/080E290C.bin"
gUnknown_080EBA78: @ 0x080EBA78
	.incbin "sound/direct_sound_samples/080EBA78.bin"
gUnknown_080F1390: @ 0x080F1390
	.incbin "sound/direct_sound_samples/080F1390.bin"
gUnknown_080F2554: @ 0x080F2554
	.incbin "sound/direct_sound_samples/080F2554.bin"
gUnknown_080F3E08: @ 0x080F3E08
	.incbin "sound/direct_sound_samples/080F3E08.bin"
gUnknown_080F6420: @ 0x080F6420
	.incbin "sound/direct_sound_samples/080F6420.bin"
gUnknown_080FA934: @ 0x080FA934
	.incbin "sound/direct_sound_samples/080FA934.bin"
gUnknown_080FBA7C: @ 0x080FBA7C
	.incbin "sound/direct_sound_samples/080FBA7C.bin"
gUnknown_080FCFDC: @ 0x080FCFDC
	.incbin "sound/direct_sound_samples/080FCFDC.bin"
gUnknown_080FD524: @ 0x080FD524
	.incbin "sound/direct_sound_samples/080FD524.bin"
gUnknown_080FFCB8: @ 0x080FFCB8
	.incbin "sound/direct_sound_samples/080FFCB8.bin"
gUnknown_08101214: @ 0x08101214
	.incbin "sound/direct_sound_samples/08101214.bin"
gUnknown_08107BD0: @ 0x08107BD0
	.incbin "sound/direct_sound_samples/08107BD0.bin"
gUnknown_08109F80: @ 0x08109F80
	.incbin "sound/direct_sound_samples/08109F80.bin"
gUnknown_0810CEF0: @ 0x0810CEF0
	.incbin "sound/direct_sound_samples/0810CEF0.bin"
gUnknown_0810F2D4: @ 0x0810F2D4
	.incbin "sound/direct_sound_samples/0810F2D4.bin"
gUnknown_0810FC48: @ 0x0810FC48
	.incbin "sound/direct_sound_samples/0810FC48.bin"
gUnknown_08111BFC: @ 0x08111BFC
	.incbin "sound/direct_sound_samples/08111BFC.bin"
gUnknown_08115300: @ 0x08115300
	.incbin "sound/direct_sound_samples/08115300.bin"
gUnknown_081166DC: @ 0x081166DC
	.incbin "sound/direct_sound_samples/081166DC.bin"
gUnknown_08117194: @ 0x08117194
	.incbin "sound/direct_sound_samples/08117194.bin"
gUnknown_081186C0: @ 0x081186C0
	.incbin "sound/direct_sound_samples/081186C0.bin"
gUnknown_08118CEC: @ 0x08118CEC
	.incbin "sound/direct_sound_samples/08118CEC.bin"
gUnknown_08119F18: @ 0x08119F18
	.incbin "sound/direct_sound_samples/08119F18.bin"
gUnknown_0811AEFC: @ 0x0811AEFC
	.incbin "sound/direct_sound_samples/0811AEFC.bin"
gUnknown_0811B800: @ 0x0811B800
	.incbin "sound/direct_sound_samples/0811B800.bin"
gUnknown_0811BFA4: @ 0x0811BFA4
	.incbin "sound/direct_sound_samples/0811BFA4.bin"
gUnknown_0811CCD4: @ 0x0811CCD4
	.incbin "sound/direct_sound_samples/0811CCD4.bin"
gUnknown_0811DB98: @ 0x0811DB98
	.incbin "sound/direct_sound_samples/0811DB98.bin"
gUnknown_0811E754: @ 0x0811E754
	.incbin "sound/direct_sound_samples/0811E754.bin"
gUnknown_081250BC: @ 0x081250BC
	.incbin "sound/direct_sound_samples/081250BC.bin"
gUnknown_08127938: @ 0x08127938
	.incbin "sound/direct_sound_samples/08127938.bin"
gUnknown_08128C7C: @ 0x08128C7C
	.incbin "sound/direct_sound_samples/08128C7C.bin"
gUnknown_0812A230: @ 0x0812A230
	.incbin "sound/direct_sound_samples/0812A230.bin"
gUnknown_0812AC74: @ 0x0812AC74
	.incbin "sound/direct_sound_samples/0812AC74.bin"
gUnknown_0812B960: @ 0x0812B960
	.incbin "sound/direct_sound_samples/0812B960.bin"
gUnknown_0812C998: @ 0x0812C998
	.incbin "sound/direct_sound_samples/0812C998.bin"
gUnknown_0812CBB0: @ 0x0812CBB0
	.incbin "sound/direct_sound_samples/0812CBB0.bin"
gUnknown_081305F4: @ 0x081305F4
	.incbin "sound/direct_sound_samples/081305F4.bin"
gUnknown_08130C24: @ 0x08130C24
	.incbin "sound/direct_sound_samples/08130C24.bin"
gUnknown_081372C4: @ 0x081372C4
	.incbin "sound/direct_sound_samples/081372C4.bin"
gUnknown_08138E48: @ 0x08138E48
	.incbin "sound/direct_sound_samples/08138E48.bin"
gUnknown_08139F1C: @ 0x08139F1C
	.incbin "sound/direct_sound_samples/08139F1C.bin"
gUnknown_0813BE10: @ 0x0813BE10
	.incbin "sound/direct_sound_samples/0813BE10.bin"
gUnknown_0813C8F4: @ 0x0813C8F4
	.incbin "sound/direct_sound_samples/0813C8F4.bin"
gUnknown_0813DE44: @ 0x0813DE44
	.incbin "sound/direct_sound_samples/0813DE44.bin"
gUnknown_0813E720: @ 0x0813E720
	.incbin "sound/direct_sound_samples/0813E720.bin"
gUnknown_0813EADC: @ 0x0813EADC
	.incbin "sound/direct_sound_samples/0813EADC.bin"
gUnknown_0813FA60: @ 0x0813FA60
	.incbin "sound/direct_sound_samples/0813FA60.bin"
gUnknown_08140550: @ 0x08140550
	.incbin "sound/direct_sound_samples/08140550.bin"
gUnknown_08140EF8: @ 0x08140EF8
	.incbin "sound/direct_sound_samples/08140EF8.bin"
gUnknown_08145C50: @ 0x08145C50
	.incbin "sound/direct_sound_samples/08145C50.bin"
gUnknown_08146624: @ 0x08146624
	.incbin "sound/direct_sound_samples/08146624.bin"
gUnknown_08147670: @ 0x08147670
	.incbin "sound/direct_sound_samples/08147670.bin"
gUnknown_08149AD0: @ 0x08149AD0
	.incbin "sound/direct_sound_samples/08149AD0.bin"
gUnknown_08149EB4: @ 0x08149EB4
	.incbin "sound/direct_sound_samples/08149EB4.bin"
gUnknown_0814F688: @ 0x0814F688
	.incbin "sound/direct_sound_samples/0814F688.bin"
gUnknown_081521DC: @ 0x081521DC
	.incbin "sound/direct_sound_samples/081521DC.bin"
gUnknown_081569D0: @ 0x081569D0
	.incbin "sound/direct_sound_samples/081569D0.bin"
gUnknown_081598CC: @ 0x081598CC
	.incbin "sound/direct_sound_samples/081598CC.bin"
gUnknown_0815AEDC: @ 0x0815AEDC
	.incbin "sound/direct_sound_samples/0815AEDC.bin"
gUnknown_0815BEB0: @ 0x0815BEB0
	.incbin "sound/direct_sound_samples/0815BEB0.bin"
gUnknown_0815E624: @ 0x0815E624
	.incbin "sound/direct_sound_samples/0815E624.bin"
gUnknown_0815ED18: @ 0x0815ED18
	.incbin "sound/direct_sound_samples/0815ED18.bin"
gUnknown_0815F364: @ 0x0815F364
	.incbin "sound/direct_sound_samples/0815F364.bin"
gUnknown_0815F898: @ 0x0815F898
	.incbin "sound/direct_sound_samples/0815F898.bin"
gUnknown_0815FBE0: @ 0x0815FBE0
	.incbin "sound/direct_sound_samples/0815FBE0.bin"
gUnknown_08162510: @ 0x08162510
	.incbin "sound/direct_sound_samples/08162510.bin"
gUnknown_08167258: @ 0x08167258
	.incbin "sound/direct_sound_samples/08167258.bin"
gUnknown_08168E6C: @ 0x08168E6C
	.incbin "sound/direct_sound_samples/08168E6C.bin"
gUnknown_0816CA60: @ 0x0816CA60
	.incbin "sound/direct_sound_samples/0816CA60.bin"
gUnknown_0816E274: @ 0x0816E274
	.incbin "sound/direct_sound_samples/0816E274.bin"
gUnknown_08172588: @ 0x08172588
	.incbin "sound/direct_sound_samples/08172588.bin"
gUnknown_08177B94: @ 0x08177B94
	.incbin "sound/direct_sound_samples/08177B94.bin"
gUnknown_08177F68: @ 0x08177F68
	.incbin "sound/direct_sound_samples/08177F68.bin"
gUnknown_0817CAF4: @ 0x0817CAF4
	.incbin "sound/direct_sound_samples/0817CAF4.bin"
gUnknown_0817F4E0: @ 0x0817F4E0
	.incbin "sound/direct_sound_samples/0817F4E0.bin"
gUnknown_08181174: @ 0x08181174
	.incbin "sound/direct_sound_samples/08181174.bin"
gUnknown_081820DC: @ 0x081820DC
	.incbin "sound/direct_sound_samples/081820DC.bin"
gUnknown_081824B0: @ 0x081824B0
	.incbin "sound/direct_sound_samples/081824B0.bin"
gUnknown_081828F4: @ 0x081828F4
	.incbin "sound/direct_sound_samples/081828F4.bin"
gUnknown_0818303C: @ 0x0818303C
	.incbin "sound/direct_sound_samples/0818303C.bin"
gUnknown_081836B8: @ 0x081836B8
	.incbin "sound/direct_sound_samples/081836B8.bin"
gUnknown_08187A8C: @ 0x08187A8C
	.incbin "sound/direct_sound_samples/08187A8C.bin"
gUnknown_0818851C: @ 0x0818851C
	.incbin "sound/direct_sound_samples/0818851C.bin"
gUnknown_08188DE8: @ 0x08188DE8
	.incbin "sound/direct_sound_samples/08188DE8.bin"
gUnknown_0818A264: @ 0x0818A264
	.incbin "sound/direct_sound_samples/0818A264.bin"
gUnknown_0818C9D0: @ 0x0818C9D0
	.incbin "sound/direct_sound_samples/0818C9D0.bin"
gUnknown_0818DB44: @ 0x0818DB44
	.incbin "sound/direct_sound_samples/0818DB44.bin"
gUnknown_0818EA28: @ 0x0818EA28
	.incbin "sound/direct_sound_samples/0818EA28.bin"
gUnknown_0818F528: @ 0x0818F528
	.incbin "sound/direct_sound_samples/0818F528.bin"
gUnknown_08190F38: @ 0x08190F38
	.incbin "sound/direct_sound_samples/08190F38.bin"
gUnknown_08191950: @ 0x08191950
	.incbin "sound/direct_sound_samples/08191950.bin"
gUnknown_0819434C: @ 0x0819434C
	.incbin "sound/direct_sound_samples/0819434C.bin"
gUnknown_08194CC8: @ 0x08194CC8
	.incbin "sound/direct_sound_samples/08194CC8.bin"
gUnknown_081964D4: @ 0x081964D4
	.incbin "sound/direct_sound_samples/081964D4.bin"
gUnknown_08197E64: @ 0x08197E64
	.incbin "sound/direct_sound_samples/08197E64.bin"
gUnknown_08199F90: @ 0x08199F90
	.incbin "sound/direct_sound_samples/08199F90.bin"
gUnknown_0819BCD4: @ 0x0819BCD4
	.incbin "sound/direct_sound_samples/0819BCD4.bin"
gUnknown_0819EFC0: @ 0x0819EFC0
	.incbin "sound/direct_sound_samples/0819EFC0.bin"
gUnknown_081A2294: @ 0x081A2294
	.incbin "sound/direct_sound_samples/081A2294.bin"
gUnknown_081A58E8: @ 0x081A58E8
	.incbin "sound/direct_sound_samples/081A58E8.bin"
gUnknown_081A8B7C: @ 0x081A8B7C
	.incbin "sound/direct_sound_samples/081A8B7C.bin"
gUnknown_081AB5A0: @ 0x081AB5A0
	.incbin "sound/direct_sound_samples/081AB5A0.bin"
gUnknown_081AF19C: @ 0x081AF19C
	.incbin "sound/direct_sound_samples/081AF19C.bin"
gUnknown_081B32F0: @ 0x081B32F0
	.incbin "sound/direct_sound_samples/081B32F0.bin"
gUnknown_081B6584: @ 0x081B6584
	.incbin "sound/direct_sound_samples/081B6584.bin"
gUnknown_081B83E4: @ 0x081B83E4
	.incbin "sound/direct_sound_samples/081B83E4.bin"
gUnknown_081B9648: @ 0x081B9648
	.incbin "sound/direct_sound_samples/081B9648.bin"
gUnknown_081BC4BC: @ 0x081BC4BC
	.incbin "sound/direct_sound_samples/081BC4BC.bin"
gUnknown_081BEA28: @ 0x081BEA28
	.incbin "sound/direct_sound_samples/081BEA28.bin"
gUnknown_081C0A24: @ 0x081C0A24
	.incbin "sound/direct_sound_samples/081C0A24.bin"
gUnknown_081C1CD8: @ 0x081C1CD8
	.incbin "sound/direct_sound_samples/081C1CD8.bin"
gUnknown_081C2AFC: @ 0x081C2AFC
	.incbin "sound/direct_sound_samples/081C2AFC.bin"
gUnknown_081C6CD0: @ 0x081C6CD0
	.incbin "sound/direct_sound_samples/081C6CD0.bin"
gUnknown_081CA2B4: @ 0x081CA2B4
	.incbin "sound/direct_sound_samples/081CA2B4.bin"
gUnknown_081CBC98: @ 0x081CBC98
	.incbin "sound/direct_sound_samples/081CBC98.bin"
gUnknown_081CD1B4: @ 0x081CD1B4
	.incbin "sound/direct_sound_samples/081CD1B4.bin"
gUnknown_081CDE5C: @ 0x081CDE5C
	.incbin "sound/direct_sound_samples/081CDE5C.bin"
gUnknown_081D0028: @ 0x081D0028
	.incbin "sound/direct_sound_samples/081D0028.bin"
gUnknown_081D29FC: @ 0x081D29FC
	.incbin "sound/direct_sound_samples/081D29FC.bin"
gUnknown_081D5EB4: @ 0x081D5EB4
	.incbin "sound/direct_sound_samples/081D5EB4.bin"
gUnknown_081D6C10: @ 0x081D6C10
	.incbin "sound/direct_sound_samples/081D6C10.bin"
gUnknown_081D9764: @ 0x081D9764
	.incbin "sound/direct_sound_samples/081D9764.bin"
gUnknown_081DB540: @ 0x081DB540
	.incbin "sound/direct_sound_samples/081DB540.bin"
gUnknown_081DCE4C: @ 0x081DCE4C
	.incbin "sound/direct_sound_samples/081DCE4C.bin"
gUnknown_081DEBCC: @ 0x081DEBCC
	.incbin "sound/direct_sound_samples/081DEBCC.bin"
gUnknown_081E0E20: @ 0x081E0E20
	.incbin "sound/direct_sound_samples/081E0E20.bin"
gUnknown_081E3394: @ 0x081E3394
	.incbin "sound/direct_sound_samples/081E3394.bin"
gUnknown_081E6268: @ 0x081E6268
	.incbin "sound/direct_sound_samples/081E6268.bin"
gUnknown_081E6FCC: @ 0x081E6FCC
	.incbin "sound/direct_sound_samples/081E6FCC.bin"
gUnknown_081E99E0: @ 0x081E99E0
	.incbin "sound/direct_sound_samples/081E99E0.bin"
gUnknown_081EABA0: @ 0x081EABA0
	.incbin "sound/direct_sound_samples/081EABA0.bin"
gUnknown_081EC9BC: @ 0x081EC9BC
	.incbin "sound/direct_sound_samples/081EC9BC.bin"
gUnknown_081EE804: @ 0x081EE804
	.incbin "sound/direct_sound_samples/081EE804.bin"
gUnknown_081F10B8: @ 0x081F10B8
	.incbin "sound/direct_sound_samples/081F10B8.bin"
gUnknown_081F3638: @ 0x081F3638
	.incbin "sound/direct_sound_samples/081F3638.bin"
gUnknown_081F4E24: @ 0x081F4E24
	.incbin "sound/direct_sound_samples/081F4E24.bin"
gUnknown_081F5D1C: @ 0x081F5D1C
	.incbin "sound/direct_sound_samples/081F5D1C.bin"
gUnknown_081F7730: @ 0x081F7730
	.incbin "sound/direct_sound_samples/081F7730.bin"
gUnknown_081F9D04: @ 0x081F9D04
	.incbin "sound/direct_sound_samples/081F9D04.bin"
gUnknown_081FE8F8: @ 0x081FE8F8
	.incbin "sound/direct_sound_samples/081FE8F8.bin"
gUnknown_081FF710: @ 0x081FF710
	.incbin "sound/direct_sound_samples/081FF710.bin"
gUnknown_08201944: @ 0x08201944
	.incbin "sound/direct_sound_samples/08201944.bin"
gUnknown_08204E8C: @ 0x08204E8C
	.incbin "sound/direct_sound_samples/08204E8C.bin"
gUnknown_08205E08: @ 0x08205E08
	.incbin "sound/direct_sound_samples/08205E08.bin"
gUnknown_08209100: @ 0x08209100
	.incbin "sound/direct_sound_samples/08209100.bin"
gUnknown_0820D38C: @ 0x0820D38C
	.incbin "sound/direct_sound_samples/0820D38C.bin"
gUnknown_0820F058: @ 0x0820F058
	.incbin "sound/direct_sound_samples/0820F058.bin"
gUnknown_08211EE4: @ 0x08211EE4
	.incbin "sound/direct_sound_samples/08211EE4.bin"
gUnknown_08215478: @ 0x08215478
	.incbin "sound/direct_sound_samples/08215478.bin"
gUnknown_082174A4: @ 0x082174A4
	.incbin "sound/direct_sound_samples/082174A4.bin"
gUnknown_082187E8: @ 0x082187E8
	.incbin "sound/direct_sound_samples/082187E8.bin"
gUnknown_0821A8CC: @ 0x0821A8CC
	.incbin "sound/direct_sound_samples/0821A8CC.bin"
gUnknown_0821B1B0: @ 0x0821B1B0
	.incbin "sound/direct_sound_samples/0821B1B0.bin"
gUnknown_0821D29C: @ 0x0821D29C
	.incbin "sound/direct_sound_samples/0821D29C.bin"
gUnknown_0821FD20: @ 0x0821FD20
	.incbin "sound/direct_sound_samples/0821FD20.bin"
gUnknown_08220A68: @ 0x08220A68
	.incbin "sound/direct_sound_samples/08220A68.bin"
gUnknown_08220DE8: @ 0x08220DE8
	.incbin "sound/direct_sound_samples/08220DE8.bin"
gUnknown_08222E6C: @ 0x08222E6C
	.incbin "sound/direct_sound_samples/08222E6C.bin"
gUnknown_082249B4: @ 0x082249B4
	.incbin "sound/direct_sound_samples/082249B4.bin"
gUnknown_08225170: @ 0x08225170
	.incbin "sound/direct_sound_samples/08225170.bin"
gUnknown_08228E9C: @ 0x08228E9C
	.incbin "sound/direct_sound_samples/08228E9C.bin"
gUnknown_08229D40: @ 0x08229D40
	.incbin "sound/direct_sound_samples/08229D40.bin"
gUnknown_0822BC5C: @ 0x0822BC5C
	.incbin "sound/direct_sound_samples/0822BC5C.bin"
gUnknown_0822C2EC: @ 0x0822C2EC
	.incbin "sound/direct_sound_samples/0822C2EC.bin"
gUnknown_0822C714: @ 0x0822C714
	.incbin "sound/direct_sound_samples/0822C714.bin"
gUnknown_0822E07C: @ 0x0822E07C
	.incbin "sound/direct_sound_samples/0822E07C.bin"
gUnknown_08230D44: @ 0x08230D44
	.incbin "sound/direct_sound_samples/08230D44.bin"
gUnknown_08231028: @ 0x08231028
	.incbin "sound/direct_sound_samples/08231028.bin"
gUnknown_08231528: @ 0x08231528
	.incbin "sound/direct_sound_samples/08231528.bin"
gUnknown_082319DC: @ 0x082319DC
	.incbin "sound/direct_sound_samples/082319DC.bin"
gUnknown_08231F94: @ 0x08231F94
	.incbin "sound/direct_sound_samples/08231F94.bin"
gUnknown_082327D8: @ 0x082327D8
	.incbin "sound/direct_sound_samples/082327D8.bin"
gUnknown_08234CFC: @ 0x08234CFC
	.incbin "sound/direct_sound_samples/08234CFC.bin"
gUnknown_0823751C: @ 0x0823751C
	.incbin "sound/direct_sound_samples/0823751C.bin"
gUnknown_08238DAC: @ 0x08238DAC
	.incbin "sound/direct_sound_samples/08238DAC.bin"
gUnknown_0823A710: @ 0x0823A710
	.incbin "sound/direct_sound_samples/0823A710.bin"
gUnknown_0823B9DC: @ 0x0823B9DC
	.incbin "sound/direct_sound_samples/0823B9DC.bin"
gUnknown_0823C690: @ 0x0823C690
	.incbin "sound/direct_sound_samples/0823C690.bin"
gUnknown_0823FA60: @ 0x0823FA60
	.incbin "sound/direct_sound_samples/0823FA60.bin"
gUnknown_082495B0: @ 0x082495B0
	.incbin "sound/direct_sound_samples/082495B0.bin"
gUnknown_0824EC74: @ 0x0824EC74
	.incbin "sound/direct_sound_samples/0824EC74.bin"
gUnknown_08254E18: @ 0x08254E18
	.incbin "sound/direct_sound_samples/08254E18.bin"
gUnknown_08260048: @ 0x08260048
	.incbin "sound/direct_sound_samples/08260048.bin"
gUnknown_0826C5FC: @ 0x0826C5FC
	.incbin "sound/direct_sound_samples/0826C5FC.bin"
gUnknown_08272DEC: @ 0x08272DEC
	.incbin "sound/direct_sound_samples/08272DEC.bin"
gUnknown_08276D50: @ 0x08276D50
	.incbin "sound/direct_sound_samples/08276D50.bin"
gUnknown_0827FC84: @ 0x0827FC84
	.incbin "sound/direct_sound_samples/0827FC84.bin"
gUnknown_082894E4: @ 0x082894E4
	.incbin "sound/direct_sound_samples/082894E4.bin"
gUnknown_0828FB04: @ 0x0828FB04
	.incbin "sound/direct_sound_samples/0828FB04.bin"
gUnknown_08294AE8: @ 0x08294AE8
	.incbin "sound/direct_sound_samples/08294AE8.bin"
gUnknown_08297864: @ 0x08297864
	.incbin "sound/direct_sound_samples/08297864.bin"
gUnknown_08299E58: @ 0x08299E58
	.incbin "sound/direct_sound_samples/08299E58.bin"
gUnknown_0829DB78: @ 0x0829DB78
	.incbin "sound/direct_sound_samples/0829DB78.bin"
gUnknown_082A0D00: @ 0x082A0D00
	.incbin "sound/direct_sound_samples/082A0D00.bin"
gUnknown_082AB364: @ 0x082AB364
	.incbin "sound/direct_sound_samples/082AB364.bin"
gUnknown_082AF394: @ 0x082AF394
	.incbin "sound/direct_sound_samples/082AF394.bin"
gUnknown_082B189C: @ 0x082B189C
	.incbin "sound/direct_sound_samples/082B189C.bin"
gUnknown_082B47D8: @ 0x082B47D8
	.incbin "sound/direct_sound_samples/082B47D8.bin"
gUnknown_082BBE6C: @ 0x082BBE6C
	.incbin "sound/direct_sound_samples/082BBE6C.bin"
gUnknown_082BE59C: @ 0x082BE59C
	.incbin "sound/direct_sound_samples/082BE59C.bin"
gUnknown_082C09D4: @ 0x082C09D4
	.incbin "sound/direct_sound_samples/082C09D4.bin"
gUnknown_082C3E5C: @ 0x082C3E5C
	.incbin "sound/direct_sound_samples/082C3E5C.bin"
gUnknown_082C568C: @ 0x082C568C
	.incbin "sound/direct_sound_samples/082C568C.bin"
gUnknown_082C8128: @ 0x082C8128
	.incbin "sound/direct_sound_samples/082C8128.bin"
gUnknown_082CA734: @ 0x082CA734
	.incbin "sound/direct_sound_samples/082CA734.bin"
gUnknown_082CDF90: @ 0x082CDF90
	.incbin "sound/direct_sound_samples/082CDF90.bin"
gUnknown_082D1608: @ 0x082D1608
	.incbin "sound/direct_sound_samples/082D1608.bin"
gUnknown_082D2E10: @ 0x082D2E10
	.incbin "sound/direct_sound_samples/082D2E10.bin"
gUnknown_082D4620: @ 0x082D4620
	.incbin "sound/direct_sound_samples/082D4620.bin"
gUnknown_082D6564: @ 0x082D6564
	.incbin "sound/direct_sound_samples/082D6564.bin"
gUnknown_082D8400: @ 0x082D8400
	.incbin "sound/direct_sound_samples/082D8400.bin"
gUnknown_082DA9C8: @ 0x082DA9C8
	.incbin "sound/direct_sound_samples/082DA9C8.bin"
gUnknown_082DC13C: @ 0x082DC13C
	.incbin "sound/direct_sound_samples/082DC13C.bin"
gUnknown_082DE438: @ 0x082DE438
	.incbin "sound/direct_sound_samples/082DE438.bin"
gUnknown_082E11D0: @ 0x082E11D0
	.incbin "sound/direct_sound_samples/082E11D0.bin"
gUnknown_082E2D4C: @ 0x082E2D4C
	.incbin "sound/direct_sound_samples/082E2D4C.bin"
gUnknown_082E43E4: @ 0x082E43E4
	.incbin "sound/direct_sound_samples/082E43E4.bin"
gUnknown_082E5450: @ 0x082E5450
	.incbin "sound/direct_sound_samples/082E5450.bin"
gUnknown_082E6784: @ 0x082E6784
	.incbin "sound/direct_sound_samples/082E6784.bin"
gUnknown_082E7B50: @ 0x082E7B50
	.incbin "sound/direct_sound_samples/082E7B50.bin"
gUnknown_082E955C: @ 0x082E955C
	.incbin "sound/direct_sound_samples/082E955C.bin"
gUnknown_082EAF80: @ 0x082EAF80
	.incbin "sound/direct_sound_samples/082EAF80.bin"
gUnknown_082EC9AC: @ 0x082EC9AC
	.incbin "sound/direct_sound_samples/082EC9AC.bin"
gUnknown_082EE024: @ 0x082EE024
	.incbin "sound/direct_sound_samples/082EE024.bin"
gUnknown_082EF4F4: @ 0x082EF4F4
	.incbin "sound/direct_sound_samples/082EF4F4.bin"
gUnknown_082F0EF4: @ 0x082F0EF4
	.incbin "sound/direct_sound_samples/082F0EF4.bin"
gUnknown_082F2D1C: @ 0x082F2D1C
	.incbin "sound/direct_sound_samples/082F2D1C.bin"
gUnknown_082F4930: @ 0x082F4930
	.incbin "sound/direct_sound_samples/082F4930.bin"
gUnknown_082F6BA4: @ 0x082F6BA4
	.incbin "sound/direct_sound_samples/082F6BA4.bin"
gUnknown_082F8B6C: @ 0x082F8B6C
	.incbin "sound/direct_sound_samples/082F8B6C.bin"
gUnknown_082FAB64: @ 0x082FAB64
	.incbin "sound/direct_sound_samples/082FAB64.bin"
gUnknown_082FD3F0: @ 0x082FD3F0
	.incbin "sound/direct_sound_samples/082FD3F0.bin"
gUnknown_082FF778: @ 0x082FF778
	.incbin "sound/direct_sound_samples/082FF778.bin"
gUnknown_08301DAC: @ 0x08301DAC
	.incbin "sound/direct_sound_samples/08301DAC.bin"
gUnknown_08304024: @ 0x08304024
	.incbin "sound/direct_sound_samples/08304024.bin"
gUnknown_08305604: @ 0x08305604
	.incbin "sound/direct_sound_samples/08305604.bin"
gUnknown_083068F0: @ 0x083068F0
	.incbin "sound/direct_sound_samples/083068F0.bin"
gUnknown_08307CBC: @ 0x08307CBC
	.incbin "sound/direct_sound_samples/08307CBC.bin"
gUnknown_0830939C: @ 0x0830939C
	.incbin "sound/direct_sound_samples/0830939C.bin"
gUnknown_0830AE34: @ 0x0830AE34
	.incbin "sound/direct_sound_samples/0830AE34.bin"
gUnknown_0830C610: @ 0x0830C610
	.incbin "sound/direct_sound_samples/0830C610.bin"
gUnknown_0830D77C: @ 0x0830D77C
	.incbin "sound/direct_sound_samples/0830D77C.bin"
gUnknown_0830F068: @ 0x0830F068
	.incbin "sound/direct_sound_samples/0830F068.bin"
gUnknown_08312CF8: @ 0x08312CF8
	.incbin "sound/direct_sound_samples/08312CF8.bin"
gUnknown_08316B4C: @ 0x08316B4C
	.incbin "sound/direct_sound_samples/08316B4C.bin"
gUnknown_08318270: @ 0x08318270
	.incbin "sound/direct_sound_samples/08318270.bin"
gUnknown_08319A34: @ 0x08319A34
	.incbin "sound/direct_sound_samples/08319A34.bin"
gUnknown_0831B490: @ 0x0831B490
	.incbin "sound/direct_sound_samples/0831B490.bin"
gUnknown_0831D054: @ 0x0831D054
	.incbin "sound/direct_sound_samples/0831D054.bin"
gUnknown_0831EB28: @ 0x0831EB28
	.incbin "sound/direct_sound_samples/0831EB28.bin"
gUnknown_08320158: @ 0x08320158
	.incbin "sound/direct_sound_samples/08320158.bin"
gUnknown_083220D8: @ 0x083220D8
	.incbin "sound/direct_sound_samples/083220D8.bin"
gUnknown_0832400C: @ 0x0832400C
	.incbin "sound/direct_sound_samples/0832400C.bin"
gUnknown_083255C4: @ 0x083255C4
	.incbin "sound/direct_sound_samples/083255C4.bin"
gUnknown_08326610: @ 0x08326610
	.incbin "sound/direct_sound_samples/08326610.bin"
gUnknown_083273E4: @ 0x083273E4
	.incbin "sound/direct_sound_samples/083273E4.bin"
gUnknown_08328134: @ 0x08328134
	.incbin "sound/direct_sound_samples/08328134.bin"
gUnknown_08329078: @ 0x08329078
	.incbin "sound/direct_sound_samples/08329078.bin"
gUnknown_0832A00C: @ 0x0832A00C
	.incbin "sound/direct_sound_samples/0832A00C.bin"
gUnknown_0832B680: @ 0x0832B680
	.incbin "sound/direct_sound_samples/0832B680.bin"
gUnknown_0832CA8C: @ 0x0832CA8C
	.incbin "sound/direct_sound_samples/0832CA8C.bin"
gUnknown_0832DB44: @ 0x0832DB44
	.incbin "sound/direct_sound_samples/0832DB44.bin"
gUnknown_0832ED70: @ 0x0832ED70
	.incbin "sound/direct_sound_samples/0832ED70.bin"
gUnknown_0832FDC4: @ 0x0832FDC4
	.incbin "sound/direct_sound_samples/0832FDC4.bin"
gUnknown_08331424: @ 0x08331424
	.incbin "sound/direct_sound_samples/08331424.bin"
gUnknown_083326F0: @ 0x083326F0
	.incbin "sound/direct_sound_samples/083326F0.bin"
gUnknown_08333D98: @ 0x08333D98
	.incbin "sound/direct_sound_samples/08333D98.bin"
gUnknown_083357F8: @ 0x083357F8
	.incbin "sound/direct_sound_samples/083357F8.bin"
gUnknown_08336E84: @ 0x08336E84
	.incbin "sound/direct_sound_samples/08336E84.bin"
gUnknown_08338CAC: @ 0x08338CAC
	.incbin "sound/direct_sound_samples/08338CAC.bin"
gUnknown_0833AD98: @ 0x0833AD98
	.incbin "sound/direct_sound_samples/0833AD98.bin"
gUnknown_0833C780: @ 0x0833C780
	.incbin "sound/direct_sound_samples/0833C780.bin"
gUnknown_0833E224: @ 0x0833E224
	.incbin "sound/direct_sound_samples/0833E224.bin"
gUnknown_0833F184: @ 0x0833F184
	.incbin "sound/direct_sound_samples/0833F184.bin"
gUnknown_0833FF80: @ 0x0833FF80
	.incbin "sound/direct_sound_samples/0833FF80.bin"
gUnknown_08340E20: @ 0x08340E20
	.incbin "sound/direct_sound_samples/08340E20.bin"
gUnknown_08341E98: @ 0x08341E98
	.incbin "sound/direct_sound_samples/08341E98.bin"
gUnknown_0834321C: @ 0x0834321C
	.incbin "sound/direct_sound_samples/0834321C.bin"
gUnknown_0834463C: @ 0x0834463C
	.incbin "sound/direct_sound_samples/0834463C.bin"
gUnknown_083453DC: @ 0x083453DC
	.incbin "sound/direct_sound_samples/083453DC.bin"
gUnknown_083558F0: @ 0x083558F0
	.incbin "sound/direct_sound_samples/083558F0.bin"
gUnknown_0835D69C: @ 0x0835D69C
	.incbin "sound/direct_sound_samples/0835D69C.bin"
gUnknown_08364D60: @ 0x08364D60
	.incbin "sound/direct_sound_samples/08364D60.bin"
gUnknown_08377BBC: @ 0x08377BBC
	.incbin "sound/direct_sound_samples/08377BBC.bin"
gUnknown_083896C4: @ 0x083896C4
	.incbin "sound/direct_sound_samples/083896C4.bin"
gUnknown_0838CE18: @ 0x0838CE18
	.incbin "sound/direct_sound_samples/0838CE18.bin"
gUnknown_083907FC: @ 0x083907FC
	.incbin "sound/direct_sound_samples/083907FC.bin"
gUnknown_08393824: @ 0x08393824
	.incbin "sound/direct_sound_samples/08393824.bin"
gUnknown_08396F2C: @ 0x08396F2C
	.incbin "sound/direct_sound_samples/08396F2C.bin"
gUnknown_083A440C: @ 0x083A440C
	.incbin "sound/direct_sound_samples/083A440C.bin"
gUnknown_083AB854: @ 0x083AB854
	.incbin "sound/direct_sound_samples/083AB854.bin"
gUnknown_083AD22C: @ 0x083AD22C
	.incbin "sound/direct_sound_samples/083AD22C.bin"
gUnknown_083B1824: @ 0x083B1824
	.incbin "sound/direct_sound_samples/083B1824.bin"
