gUnknown_0804EC90: @ 0x0804EC90
	.incbin "sound/programmable_wave_samples/0804EC90.pcm"
gUnknown_0804ECA0: @ 0x0804ECA0
	.incbin "sound/programmable_wave_samples/0804ECA0.pcm"
gUnknown_0804ECB0: @ 0x0804ECB0
	.incbin "sound/programmable_wave_samples/0804ECB0.pcm"
gUnknown_0804ECC0: @ 0x0804ECC0
	.incbin "sound/programmable_wave_samples/0804ECC0.pcm"
gUnknown_0804ECD0: @ 0x0804ECD0
	.incbin "sound/programmable_wave_samples/0804ECD0.pcm"
gUnknown_0804ECE0: @ 0x0804ECE0
	.incbin "sound/programmable_wave_samples/0804ECE0.pcm"
gUnknown_0804ECF0: @ 0x0804ECF0
	.incbin "sound/programmable_wave_samples/0804ECF0.pcm"
gUnknown_0804ED00: @ 0x0804ED00
	.incbin "sound/programmable_wave_samples/0804ED00.pcm"
gUnknown_0804ED10: @ 0x0804ED10
	.incbin "sound/programmable_wave_samples/0804ED10.pcm"
gUnknown_0804ED20: @ 0x0804ED20
	.incbin "sound/programmable_wave_samples/0804ED20.pcm"
gUnknown_0804ED30: @ 0x0804ED30
	.incbin "sound/programmable_wave_samples/0804ED30.pcm"
gUnknown_0804ED40: @ 0x0804ED40
	.incbin "sound/programmable_wave_samples/0804ED40.pcm"
gUnknown_0804ED50: @ 0x0804ED50
	.incbin "sound/programmable_wave_samples/0804ED50.pcm"
gUnknown_0804ED60: @ 0x0804ED60
	.incbin "sound/programmable_wave_samples/0804ED60.pcm"
gUnknown_0804ED70: @ 0x0804ED70
	.incbin "sound/programmable_wave_samples/0804ED70.pcm"
