	.align 2, 0
	.global voicegroup000
voicegroup000: @ 0x0804CE78 (voicegroup)
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 2, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 2, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 2, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 2, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 2, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 15, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0
	voice_square_1_alt 60, 0, 0, 2, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 1, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 0, 0, 4, 0, 0
	voice_square_1_alt 60, 0, 0, 3, 1, 0, 15, 2
	voice_square_1_alt 60, 0, 0, 2, 0, 6, 0, 0
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 3, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 3, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 0, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 2, 2, 0, 15, 0
	voice_square_2_alt 60, 0, 3, 2, 0, 15, 0
	voice_square_2_alt 60, 0, 0, 2, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 2, 4, 0, 0
	voice_square_2_alt 60, 0, 3, 2, 4, 0, 0
	voice_square_2_alt 60, 0, 0, 2, 4, 0, 0
	voice_square_2_alt 60, 0, 2, 0, 4, 15, 0
	voice_square_2_alt 60, 0, 3, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 3, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 0, 0, 4, 0, 0
	voice_square_2_alt 60, 0, 0, 1, 0, 15, 2
	voice_square_2_alt 60, 0, 3, 0, 6, 0, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, gUnknown_08050968, 255, 0, 255, 127
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 6, 0
	voice_keysplit voicegroup003, KeySplitTable1
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED20, 0, 0, 15, 1
	voice_noise_alt 60, 0, 1, 0, 0, 15, 4
	voice_programmable_wave_alt 60, 0, gUnknown_0804EC90, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECA0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECB0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECC0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECD0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECE0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECF0, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED00, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED10, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED20, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED30, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED40, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED50, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED60, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED70, 0, 0, 15, 0
	voice_directsound 60, 0, gUnknown_08052EA4, 255, 0, 255, 127
	voice_directsound 60, 0, gUnknown_08055078, 255, 0, 255, 127
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECC0, 0, 2, 8, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECB0, 0, 2, 8, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECB0, 0, 2, 0, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECC0, 0, 2, 0, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804EC90, 2, 0, 15, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ECE0, 0, 4, 0, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED20, 0, 2, 8, 0
	voice_programmable_wave_alt 60, 0, gUnknown_0804ED60, 0, 1, 0, 0
	voice_directsound_no_resample 60, 0, gUnknown_08057180, 255, 0, 255, 165
	voice_directsound 60, 0, gUnknown_08059E48, 255, 0, 255, 165
	voice_directsound 60, 0, gUnknown_0805B61C, 255, 0, 255, 127
	voice_directsound 60, 0, gUnknown_0805DE78, 255, 0, 255, 165
	voice_directsound 60, 0, gUnknown_0805E7C4, 255, 0, 255, 165
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.size voicegroup000,.-voicegroup000
